/**
 * Bundle D1: small chip that surfaces *who* generated the incident's
 * reason text — the live Gemini model or our canned fallback. Renders
 * nothing when triage_source is unknown so legacy/seeded incidents stay
 * visually clean.
 *
 * Used in:
 *   - features/incidents/IncidentsPage row tail
 *   - features/incidents/IncidentDetailPage hero
 *   - features/evidence/EvidencePage reason block
 */

type TriageSourceChipProps = {
  source?: string | null;
  model?: string | null;
  latencyMs?: number | null;
  size?: "sm" | "md";
};

export function TriageSourceChip({
  source,
  model,
  latencyMs,
  size = "sm",
}: TriageSourceChipProps) {
  if (!source) return null;

  const isGemini = source === "gemini";
  const cls = isGemini
    ? "triage-chip triage-chip--gemini"
    : "triage-chip triage-chip--fallback";

  // Gemini path: "Gemini · gemini-2.5-flash · 1.2 s"
  // Fallback path: "Canned reason"
  const label = isGemini ? "Gemini" : "Canned reason";
  const detail =
    isGemini && (model || typeof latencyMs === "number")
      ? [model, typeof latencyMs === "number" ? `${(latencyMs / 1000).toFixed(1)} s` : null]
          .filter(Boolean)
          .join(" · ")
      : "";

  return (
    <span
      className={`${cls} triage-chip--${size}`}
      title={
        isGemini
          ? `Reason text generated by ${model ?? "Gemini"}${
              typeof latencyMs === "number" ? ` in ${(latencyMs / 1000).toFixed(2)} s` : ""
            }`
          : "Reason text from the canned fallback (Gemini was unavailable, rate-limited, or unconfigured)"
      }
    >
      <span className="triage-chip__dot" aria-hidden />
      <span className="triage-chip__label">{label}</span>
      {detail && <span className="triage-chip__detail">{detail}</span>}
    </span>
  );
}
