from typing import Optional

from pydantic import BaseModel


class AssetSummary(BaseModel):
    asset_id: str
    title: str
    asset_type: str
    event_name: str
    status: str
    provenance_status: str
    incident_count: int
    preview_path: Optional[str] = None


class AssetListResponse(BaseModel):
    items: list[AssetSummary]


class AssetCreateRequest(BaseModel):
    title: str
    asset_type: str = "image"
    event_name: Optional[str] = None
    sport: Optional[str] = None
    rights_owner: Optional[str] = None
    description: Optional[str] = None
    provenance_status: str = "present"


class AssetCreateResponse(BaseModel):
    id: str
    upload_url: str


class AssetMatchSummary(BaseModel):
    """One row of matcher output surfaced back to the upload caller.

    The frontend uses this to render the post-upload toast and tell the user
    how many incidents were created from their new asset.
    """

    feed_item_id: str
    similarity_score: float
    confidence_band: str
    severity: str
    incident_id: Optional[str] = None
    triage_source: Optional[str] = None  # 'gemini' | 'fallback' | None
    synthetic: bool = False  # True when feed item was generated by demo fallback


class AssetDetail(BaseModel):
    id: str
    title: str
    asset_type: str
    event_name: Optional[str] = None
    sport: Optional[str] = None
    rights_owner: Optional[str] = None
    description: Optional[str] = None
    status: str
    provenance_status: str
    primary_path: Optional[str] = None
    preview_path: Optional[str] = None
    phash: Optional[str] = None
    created_at: str
    incident_count: int

    # Bundle B: populated only by the upload endpoint, otherwise empty list.
    matches: list[AssetMatchSummary] = []
